version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/deploy
hooks:
  BeforeInstall:
    - location: bitbucket-pipelines/beforeInstall.sh
      runas: root
  AfterInstall:
    - location: bitbucket-pipelines/afterInstall.sh
      runas: root
