<?php

/**
 * @file
 * Contains custom_module_seba.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_module_seba_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the custom_module_seba module.
    case 'help.page.custom_module_seba':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module Seba') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_module_seba_theme()
{
  $themes['custom_module_seba'] = [
    'render element' => 'children',
  ];

  $themes['profile_form'] = [
    'render element' => 'form',
  ];

  return $themes;
}
