<?php

/**
 * @file
 * Contains programacion.module.
 */


function programacion_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'programacion/programacion-testjs-library';
}

/**
 * Implements hook_theme().
 */
function programacion_theme($existing, $type, $theme, $path)
{
    $themes['theme_test1'] = [
        'template' => 'test1',
        'variables' => array('array_vars' => NULL),
    ];
    return $themes;
}