<?php

/**
 * @file
 * Contains profile_seba.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function profile_seba_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the profile_seba module.
    case 'help.page.profile_seba':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Profile Seba') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function profile_seba_theme() {
  return [
    'profile_seba' => [
      'render element' => 'children',
    ],
  ];
}
