<?php

/**
 * @file
 * Contains custom_module_jere.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_module_jere_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
      // Main module help for the custom_module_jere module.
    case 'help.page.custom_module_jere':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module Jere') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_module_jere_theme($existing, $type, $theme, $path)
{
  $themes['custom_module_jere'] = [
    'render element' => 'children',

  ];
  $themes['profile_form'] = [
    'render element' => 'form',
  ];

  return $themes;
}
