<?php

/**
 * @file
 * Contains basic_test.module.
 */


function basic_test_page_attachments(array &$attachments)
{
    $attachments['#attached']['library'][] = 'basic_test/basic-test-library';
}

/**
 * Implements hook_theme().
 */
function basic_test_theme($existing, $type, $theme, $path)
{
    $themes['basic_test_theme_test'] = [
        'template' => 'basic-test',
        'variables' => array('vars' => NULL),
    ];

    $themes['success_insert_twig'] = [
        'template' => 'inserts',
        'variables' => array('vars' => NULL),
    ];

    $themes['list_page'] = [
        'template' => 'list_inserts',
        'variables' => array('vars' => NULL),
    ];

    return $themes;
}