<?php

/**
 * @file
 * Contains custom_module_d21.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_module_d21_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_module_d21 module.
    case 'help.page.custom_module_d21':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Module Drupal Local 21') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_module_d21_theme() {
  return [
    'custom_module_d21' => [
      'render element' => 'children',
    ],
  ];
}
